

@clientid=
@clientsecret=
@tenantid=
@fhirurl=


### Get access token 
# @name getAADToken 
POST https://login.microsoftonline.com/{{tenantid}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&resource={{fhirurl}}
&client_id={{clientid}}
&client_secret={{clientsecret}}
&scope={{fhirurl}}/.default

### Extract access token from getAADToken request
@token = {{getAADToken.response.body.access_token}}

### GET Patient 
GET {{fhirurl}}/Patient/3737c013-8418-42a4-b9ca-fe2663ab26dc
Authorization: Bearer {{token}}




### Test the API for fetching John Doe's data from Neo4j
GET http://localhost:3001/api/patient/Jane%20Smith
Content-Type: application/json
